[package]
name = "common_macros"
description = "A crate to hold common macros"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
