[package]
name = "adapter_repositories_mongodb"
description = "MongoDB-specific repositories implementation"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
