[package]
name = "kernel_services"
description = "A crate to hold services' traits and abstract code"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
# project dependencies
kernel_entities = { path = "../entities" }

# workspace dependencies
async-trait = { workspace = true }
