[workspace]
members = ["crates/domain/*", "crates/common/*"]

[workspace.package]
edition = "2021"
version = "0.0.1"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]

[workspace.dependencies]
uuid = { version = "1.2.1", features = ["v4"] }
chrono = "0.4"
