[workspace]
members = ["crates/common/*", "crates/kernel/*", "crates/driver/*"]

[workspace.package]
edition = "2021"
version = "0.0.1"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]

[workspace.dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
chrono = "0.4"
derive_more = "0.99.17"
thiserror = "1.0"
uuid = { version = "1.2.1", features = ["v4"] }
