version: '3'

services:
  postgres:
    image: postgres
    container_name: asma_data
    restart: always
    environment:
      POSTGRES_PASSWORD: 123

  mongo:
    image: mongo
    container_name: asma_doc
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo
    depends_on:
      - mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 5 && mongosh --host mongo:27017 --eval 'rs.initiate()'"]

  rabbitmq:
    image: rabbitmq
    container_name: asma_ipc
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: asma
      RABBITMQ_DEFAULT_PASS: asma

  app:
    build: .
    container_name: asma
    restart: always
    depends_on:
      - postgres
      - mongo
      - mongosetup
      - rabbitmq
    ports:
      - 8080:8080
      - 8888:8888
