[package]
name = "data_entities"
description = "A crate to hold entites used in data-oriented operations"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
