[package]
name = "driver_web_rest"
description = "HTTP RESTful API host using tokio/axum"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
# crate dependencies
axum = "0"
shaku_axum = "0"
utoipa = { version = "2", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "2", features = ["axum"] }

# workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
