[package]
name = "data_entities"
description = "A crate to hold entites used in data-oriented operations"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
# project dependencies
domain_proc_macros = { path = "../proc_macros" }

# workspace dependencies
uuid = { workspace = true }
chrono = { workspace = true }

# crate dependencies
validator = { version = "^0", features = ["derive"] }
